import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
const Poppinss = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Organic Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Poppinss.className}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow w-[1200px] mx-auto"> {children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
